### ISSUE TITLE
Could not import PILLOW_VERSION from PIL

### ISSUE THREAD

**Issue by swingcake** [M4rt1nM4yr/spatio-temporal_handwriting_imitation#2]
The following error is encountered:
`from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL'`

This has been fixed in torchvision [v0.5.0](https://github.com/pytorch/vision/releases/tag/v0.5.0). To fix:
- Require `torchvision>=0.5.0`

**Comment by M4rt1nM4yr** [comment]
Thank you for your contribution.
